name: Deploy to staging

on:
  push:
    branches:
      - production  # Trigger only when the 'production' branch is pushed

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Deploy
        run: |
          # Write private SSH key to a file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          # SSH into the server and run deployment commands
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@3.109.122.195 << 'EOF'
            # Load NVM and use Node.js v22
            export NVM_DIR=$HOME/.nvm
            source $NVM_DIR/nvm.sh
            nvm use 22

            # Navigate to app directory and reset to clean state
            cd week-25-ci-next-app
            git reset --hard HEAD
            git clean -fd
            git pull origin production

            # Node and package setup
            node -v
            npm -v
            npm install -g pnpm
            pnpm -v
            pnpm install

            # Build and restart processes
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
