name: Deploy to staging

on:
  push:
    branches:
      - production

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -i ~/ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@3.109.122.195 "
            export NVM_DIR=\$HOME/.nvm &&
            source \$NVM_DIR/nvm.sh &&
            nvm use 22 &&

            # Go to the project directory and get the latest production branch
            cd week-25-ci-next-app &&
            git fetch origin production &&
            git checkout production &&
            git reset --hard origin/production &&
            git clean -fd &&

            # Create .env file inside packages/prisma
            echo \"DATABASE_URL=${{ secrets.DATABASE_URL }}\" > packages/prisma/.env &&

            # Build and restart services
            node -v &&
            npm -v &&
            npm install -g pnpm &&
            pnpm -v &&
            pnpm install &&
            pnpm run build &&

            pm2 restart fe-server &&
            pm2 restart http-server &&
            pm2 restart ws-server
          "
